from os import environ

# NetBox is served under https://rep.local.inion/netbox/
BASE_PATH = environ.get("BASE_PATH", "netbox/")

# --- Single sign-on (Keycloak -> oauth2-proxy -> Nginx auth_request) ---
# REMOTE_AUTH_* come from .env (gen-env.sh): users are identified by X-Remote-User,
# groups are synced from X-Remote-Groups on every login, members of
# netbox-admins become superusers.
#
# NetBox cannot express "view everything" in REMOTE_AUTH_DEFAULT_PERMISSIONS (no
# wildcards), so read-only access is an ObjectPermission (actions=['view'], all
# object types) bound to the SSO groups — created by deploy/netbox/post-install.py.
REMOTE_AUTH_DEFAULT_PERMISSIONS = {}

# v2 API tokens (NetBox 4.5+) need at least one pepper (>= 50 chars), generated by gen-env.sh.
# Without it tokens cannot be created in the UI. Legacy v1 tokens keep working.
_pepper = environ.get("API_TOKEN_PEPPER_1", "")
if _pepper:
    API_TOKEN_PEPPERS = {1: _pepper}
